#!/bin/sh


/usr/bin/grep -E "CAABR|CAAXM|CAAXT|CAAXB|CAAXW|CABTP|CABPK|CAHSB|CABP6|CABP8|CACMP|CACNM|CACBP|CACWP|CACB1|CADYN|CAEGE|CAELT|CAFLC|CAGDH|CAGMS|CACL9|CALOG|CACCK|CANWD|CAHPK|CAINP|CAIRW|CAKDL|CALVP|CAMLP|CAMNP|CAMON|CAPBA|CAPTY|CARIC|CASCP|CASBK|CABLD|CABRN|CATLS|CAALT|CAELK|CASMB|CAALP|CA42R|CASWP|CATEL|CAVBS|CAVCB|CAVMM|CAVPQ|CAVLP|CAWCP|CALXV|CAMTZ|CALT9|CABAR|CAJDF|CAKTP|CASGM|CAMXC" ~/obs/static/csv/madis-stations.csv

exit 0
