#!/bin/sh

mod-title.sh rip.in.rtcloud
mod-title.sh rip.in.rtflux
mod-title.sh rip.in.rthaines
mod-title.sh rip.in.rtlapscloud
mod-title.sh rip.in.rtlapshaines
mod-title.sh rip.in.rtlapspbl
mod-title.sh rip.in.rtlapsprecip
mod-title.sh rip.in.rtlapsprecip-1
mod-title.sh rip.in.rtlapsradar
mod-title.sh rip.in.rtlapsrh
mod-title.sh rip.in.rtlapssnow
mod-title.sh rip.in.rtlapsspd
mod-title.sh rip.in.rtlapstd
mod-title.sh rip.in.rtlapstemp
mod-title.sh rip.in.rtlapstpw
mod-title.sh rip.in.rtlapstype
mod-title.sh rip.in.rtlapsupa
mod-title.sh rip.in.rtlhflux
mod-title.sh rip.in.rtmocarh
mod-title.sh rip.in.rtmocaspd
mod-title.sh rip.in.rtmocatd
mod-title.sh rip.in.rtmocatemp
mod-title.sh rip.in.rtpbl
mod-title.sh rip.in.rtprecip
mod-title.sh rip.in.rtprecip-24
mod-title.sh rip.in.rtradar
mod-title.sh rip.in.rtrh
mod-title.sh rip.in.rtshflux
mod-title.sh rip.in.rtsnow
mod-title.sh rip.in.rtspd
mod-title.sh rip.in.rttd
mod-title.sh rip.in.rttemp
mod-title.sh rip.in.rttpw
mod-title.sh rip.in.rttype
mod-title.sh rip.in.rtupa

exit 0
